Document ARM support
open-telemetry/opentelemetry-go-instrumentation pull request #160
Opened 2023-05-15 18:03 UTC by MrAlias

Resolve https://github.com/open-telemetry/opentelemetry-go-instrumentation/issues/132

2023-05-15 19:05 UTC, JamieDanielson commented on README.md
> +Be sure to validate support on your own ARM bases system.
```suggestion
Be sure to validate support on your own ARM based system.
```

2023-05-15 20:35 UTC, JamieDanielson approved these changes

2023-05-16 06:55 UTC, pellared requested changes

2023-05-16 06:55 UTC, pellared commented on README.md
> +Windows users should currently use Docker/VM to compile and run this repository.
This is not only about Windows 😉 

```suggestion
Users of non-Linux operating systems can use
[the Docker images](https://github.com/open-telemetry/opentelemetry-go-instrumentation/pkgs/container/opentelemetry-go-instrumentation%2Fautoinstrumentation-go)
or create a virtual machine to compile and run OpenTelemetry Go Automatic Instrumentation.
```

2023-05-16 06:55 UTC, pellared commented on README.md
> +This project supports the ARM platform.
```suggestion
OpenTelemetry Go Automatic Instrumentation supports the arm64 architecture.
```

arm64 is the "key" change.

2023-05-16 11:15 UTC, MikeGoldsmith approved these changes
Pending @pellared's review comments, this looks good to me 👍🏻

2023-05-16 14:42 UTC, merged