Example K8s-grafana deployment
open-telemetry/opentelemetry-go-instrumentation pull request #37
Opened 2023-03-09 14:54 UTC by mariomac

To be merged after https://github.com/open-telemetry/opentelemetry-go-instrumentation/pull/32

Simple deployment to demonstrate the instrumentation without requiring any extra launcher.

2023-03-09 17:39 UTC, edeNFed commented on deployments/grafana-demo/02-auto-instrument.yml
> +kind: DaemonSet
Why not deploy it as a sidecar container in the goblog deployment? 
Deploying it as a DaemonSet would only instrument a single process even if you deploy multiple instances of the goblog application.

2023-03-17 20:29 UTC, dineshg13 commented on deployments/grafana-demo/02-auto-instrument.yml
> +    }
Can we use local graphana or prometheus ? In opentelemetry-demo, we use same https://github.com/open-telemetry/opentelemetry-demo/blob/5f7517aad8e2f1365c7d4b173194bfdba2da4489/docker-compose.yml#L624

2023-03-17 20:30 UTC, dineshg13 requested changes
Can we rewrite example to use deployed version of graphana or prometheus rather than remote one

2023-03-17 20:30 UTC, dineshg13 commented on deployments/grafana-demo/00-demo-app.yml
> +          image: mariomac/goblog:dev
How is this image build ?

2023-03-21 16:44 UTC, mariomac commented
Closing this PR as, thinking it twice, it has too many issues to be part of the standard documentation/examples. (e.g. the demo application is just a personal container)

2023-03-21 16:44 UTC, closed without merging