Adding net/http client instrumentor
open-telemetry/opentelemetry-go-instrumentation pull request #91
Opened 2023-04-24 06:51 UTC by oxeye-gal

Hi,

This PR attempts to add instrumentation for net/http client.

We do it by writing a fake tophash value (as calculating the correct one will be harder to achieve) to the first headers map bucket and writing the "traceparent" header key and value into memory.

This was tested with Go versions 1.12-1.19.

Our test environment consisted of instrumented Python application that sends a request to instrumented Go http server which in turn sends an http request to an additional instrumented Go http server.

The produced trace looks like the following:

![213374473-d266bf1f-49f5-4f8c-8e0d-53ed51d80201](https://user-images.githubusercontent.com/97847098/233919703-dae47f1a-3f61-4fe8-8ecf-249af4b20ebb.png)

We would love to get your feedback on this.
Thanks!

2023-04-24 20:58 UTC, damemi requested changes
@oxeye-gal looks like this updates the test fixtures (which is expected since this is a new instrumentation) based on the [CI failure](https://github.com/open-telemetry/opentelemetry-go-instrumentation/actions/runs/4783367077/jobs/8520701861?pr=91#step:17:45)

If you have [kind](https://kind.sigs.k8s.io/) installed, you should be able to run `make fixture-nethttp` to re-generate the test output and commit the result.

2023-05-03 06:40 UTC, MikeGoldsmith commented
Hey @oxeye-gal - this PR needs rebasing after we merged ARM support on #82. I’m happy to help do that if you would like us to.

2023-05-23 17:46 UTC, MikeGoldsmith commented
@oxeye-gal now #92 has been merged, I’ll look to update this PR too 👍🏻

2023-06-06 10:56 UTC, MikeGoldsmith commented
Picking this up now - sorry it's taken longer than expected to get back to.

2023-06-12 11:30 UTC, MikeGoldsmith commented
@oxeye-gal please could you "update branch" one more time, and we can merge this PR :)

2023-06-12 11:31 UTC, MikeGoldsmith approved these changes

2023-06-12 11:33 UTC, MikeGoldsmith commented
@open-telemetry/go-instrumentation-approvers Please can you review this PR - it needs a final "update branch" but once done I'd like to merge this. I've worked up making sure it works and plan on expanding the same work to the other HTTP probes once it's done (see #101).

2023-06-12 11:43 UTC, pdelewski commented on pkg/instrumentors/bpf/net/http/client/bpf/probe.bpf.c
> +    void *injected_key_ptr = map_keyvalues_ptr + 8 + (16 * map_keyvalue_count);
Can we use constants instead of number literals?

2023-06-14 09:25 UTC, pdelewski approved these changes

2023-06-14 09:32 UTC, edeNFed approved these changes
lgtm

2023-06-14 09:33 UTC, merged